version: '3'

services:
  tendermint1:
    image: tendermint/tendermint:latest
    command: sh -c "tendermint init; node --proxy_app=tcp://abci1:46659 --p2p.seeds=tendermint2:46656"
    entrypoint: /bin/sh
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 4444:46657
    volumes:
      - tendermint1dv:/tendermint
    links :
      - abci1

  abci1:
    build: .
    restart: always
    environment:
      - PORT=46659
    volumes:
      - tendermint1dv:/tendermint
    ports:
      - 8888:46659

  tendermint2:
    image: tendermint/tendermint:latest
    command: sh -c "tendermint init; node --proxy_app=tcp://abci2:46660 --p2p.seeds=tendermint1:46656"
    entrypoint: /bin/sh
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 4445:46657
    volumes:
      - tendermint2dv:/tendermint
    links :
      - abci2
      - tendermint1

  abci2:
    build: .
    restart: always
    environment:
      - PORT=46660
    ports:
      - 8889:46659
    volumes:
      - tendermint2dv:/tendermint


volumes:
  tendermint1dv:
  tendermint2dv:
